pipeline {
     agent { label 'Docker' }
    environment {
             SONARQUBE = credentials('sonar-scanner') // Jenkins credential for token
            }  
        stages {
            stage('Checkout') {
 steps {
 git branch: 'master', url: 'https://github.com/Naveen-ASJ/jenkins.git'
 }
 }
 stage('Build') {
 steps {
 dir('javaapp-standalone') {
 sh "mvn clean package -DskipTests"
 }
 }
 }
 stage('Test') {
 steps {
 dir('javaapp-standalone') {
 sh "mvn test"
 }
 }
 }
 stage('SonarQube Analysis') {
 steps {
 withSonarQubeEnv('sonar-scanner') { // must match configured name
 sh '''
 cd javaapp-standalone
 mvn clean verify sonar:sonar \
  -Dsonar.projectKey=sonar \
  -Dsonar.host.url=http://107.20.53.49:9000 \
  -Dsonar.login=squ_d57a7720f082c53ba67b8b9903f7f469c1ba1576
 '''
 }
 }
 }
 stage('Trivy FS Scan') {
 steps {
 dir('javaapp-standalone') {
 sh "trivy fs --exit-code 0 --severity HIGH,CRITICAL ."
 }
 }
 }
 stage('Build Docker Image') {
 steps {
 dir('javaapp-standalone') {
 sh "docker build -t myapp:latest ."
 }
 }
 }
 stage('Trivy Image Scan') {
 steps
{
 sh """
 export TRIVY_CACHE_DIR=/tmp/trivy
 trivy image --scanners vuln --exit-code 0 --severity HIGH,CRITICAL myapp:latest
 """
 }
 }
 stage('Push to ECR') {
 steps {
 sh """
 aws ecr get-login-password --region us-east-1 | docker login --username AWS --
password-stdin 337909742575.dkr.ecr.us-east-1.amazonaws.com &&
 docker tag myapp:latest 337909742575.dkr.ecr.us-east-1.amazonaws.com/javaapp-image:latest &&
 docker push 337909742575.dkr.ecr.us-east-1.amazonaws.com/javaapp-image:latest
 """
 }
 }
 stage('Deploy') {
 steps {
 sh """
 docker stop myapp || true &&
 docker rm -f myapp || true &&
 docker pull 337909742575.dkr.ecr.us-east-1.amazonaws.com/javaappimage:latest &&
 docker run -d --name myapp -p 5000:5000 337909742575.dkr.ecr.us-east-1.amazonaws.com/javaapp-image:latest
 """
 script {
 def PUBLIC_IP = sh(
 script: "curl -s http://checkip.amazonaws.com",
 returnStdout: true
 ).trim()
 echo "==================================================="
 echo " Application deployed successfully! 🎉"
 echo " Access it here: http://${PUBLIC_IP}:5000"
 echo "==================================================="
 }
 }
 }
 }
}
